### ISSUE TITLE
Ajouter les liens des différentes fictions

### ISSUE THREAD

**Issue by Pverte** [Zenigata/audiodramabot#20]
Ce serait cool d'avoir un endroit pour répertorier le lien rss, le site, le deezer, spotify...

**Comment by Zenigata** [comment]
Tu voudrais qu'il y ait plusieurs liens qui s'affichent sur le détail de la fiction ?

**Comment by Pverte** [comment]
Yep

Le jeu. 4 mars 2021 à 11:43, Johan Bonneau <notifications@github.com> a
écrit :

**Comment by Zenigata** [comment]
OK je note la fonctionnalité. Après, il peut y avoir tellement de liens différents comme chacun peut utiliser ce qu'il veut... Mais ce n'est pas compliqué à faire pour au moins avoir YouTube, Spotify, RSS et site web :)

**Comment by Zenigata** [comment]
Je n'ai pas mis Deezer pour le moment.
